[project]
name = "testapi"
version = "0.1.0"
description = "testapi using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "celery[redis]>=5.6.3",
    "crewai-tools>=1.14.3",
    "crewai[tools]==1.14.3",
    "fastapi[all]>=0.136.1",
    "redis<6.5",
    "uvicorn>=0.46.0",
]

[project.scripts]
testapi = "testapi.main:run"
run_crew = "testapi.main:run"
train = "testapi.main:train"
replay = "testapi.main:replay"
test = "testapi.main:test"
run_with_trigger = "testapi.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
